{% set name = "pgdumplib" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgdumplib-{{ version }}.tar.gz
  sha256: c8a6a9158296fe06e5053c5dd65d16e734821261dc58c1573c5d4c0c1a594db4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pendulum
    - toposort

test:
  imports:
    - pgdumplib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gmr/pgdumplib
  summary: Python3 library for working with pg_dump files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cezary17
