{% set name = "pgdumplib" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgdumplib-{{ version }}.tar.gz
  sha256: b367290c9976e6c868a6b08054ca46fbf02c9764166b522c98a31ec387dfc54e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pendulum
    - toposort

test:
  imports:
    - pgdumplib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gmr/pgdumplib
  summary: Python3 library for working with pg_dump files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cezary17
